### ISSUE TITLE
P1Pro-V3请求支持

### ISSUE THREAD

**Issue by 99477204** [cx3Y/sunlogin#5]
手里有C2-BLE一切正常。双十一买了P1Pro完美支持，插排有问题换购变成了P1Pro-V3，虽然也能在HA识别到，但是实体的状态都是不可用。固件版本1.0.0，HA上显示的固件版本号是0.0.0。
![1](https://github.com/user-attachments/assets/8e114a77-237c-4e0b-8e29-c55e57857900)
2024-12-01 18:12:04.929 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-01 18:12:14.930 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-01 18:12:19.841 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1047, in _async_update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 542, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/sensor.py", line 322, in native_value
    if not prop.range_min() <= val <= prop.range_max():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
2024-12-01 18:12:24.929 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-01 18:12:34.929 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-01 18:12:44.929 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JDY9H3SMKJQN0WCJFXMY8R02) executing task devices_update
2024-12-01 18:12:44.930 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.001 seconds (success: True)
2024-12-01 18:12:45.307 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] Devices update success
2024-12-01 18:12:49.844 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1047, in _async_update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 542, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/sensor.py", line 322, in native_value
    if not prop.range_min() <= val <= prop.range_max():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
2024-12-01 18:12:54.930 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JDY9H3SMKJQN0WCJFXMY8R02) executing task config_update
2024-12-01 18:12:54.930 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JDY9H3SMKJQN0WCJFXMY8R02) executing task 智能插线板P1Pro-V3(738583) status_update
2024-12-01 18:12:54.931 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JDY9H3SMKJQN0WCJFXMY8R02) executing task 智能插线板P1Pro-V3(738583) electric_update
2024-12-01 18:12:54.931 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JDY9H3SMKJQN0WCJFXMY8R02) executing task 智能插座C2-BLE (蓝牙版)(583250) status_update
2024-12-01 18:12:54.932 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JDY9H3SMKJQN0WCJFXMY8R02) executing task 智能插座C2-BLE (蓝牙版)(583250) electric_update
2024-12-01 18:12:54.932 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.001 seconds (success: True)
2024-12-01 18:12:55.326 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_electric): {"vol":235684,"curr":0,"power":0,"result":0}
2024-12-01 18:12:55.332 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_status): {"response":[{"index":0,"status":0}],"led":1,"def_st":2,"result":0}
2024-12-01 18:13:04.929 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-01 18:13:14.929 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-01 18:13:19.828 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1047, in _async_update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 542, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/sensor.py", line 322, in native_value
    if not prop.range_min() <= val <= prop.range_max():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
2024-12-01 18:13:24.929 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JDY9H3SMKJQN0WCJFXMY8R02) executing task token_update
2024-12-01 18:13:24.930 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.001 seconds (success: True)
2024-12-01 18:13:25.131 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] Refresh token success
2024-12-01 18:13:34.930 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-01 18:13:44.929 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-01 18:13:49.850 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1047, in _async_update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 542, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/xiaomi_miot/sensor.py", line 322, in native_value
    if not prop.range_min() <= val <= prop.range_max():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
2024-12-01 18:13:54.929 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)

**Comment by SDAU10434** [comment]
哥们，最后解决了嘛

**Comment by jayhuangz** [comment]
一样的问题，同一局域网也没法通过 IP 添加，提示：Unknown error occurred

另外，HA 无法控制以后把集成删掉了，重新添加的时候无法登录了，验证码总是提示错误：身份验证失败。 verify/empty_code

最后通过扫码登录上来了，添加以后跟楼主一样的情况，无法控制。

P1Pro-V3
制造商：SunLogin
固件：0.0.0

**Comment by cx3Y** [comment]
我发布新版本，手动下载release或者在hacs里面点击redownload打开显示beta版本就能更新了

**Comment by 99477204** [comment]
P1Pro-V3在3.0.3beta依旧不可用


         原始邮件
         
       
发件人：                  "cx3Y"         ***@***.***&gt;                 
发件时间：         2024年12月15日 10:22 
收件人：                  "cx3Y/sunlogin"         ***@***.***&gt;                 
抄送：                  "99477204"         ***@***.***&gt;         ,                "Author"         ***@***.***&gt;                 
主题：         Re: [cx3Y/sunlogin] P1Pro-V3请求支持 (Issue #5) 




我发布新版本，手动下载release或者在hacs里面点击redownload打开显示beta版本就能更新了

**Comment by 99477204** [comment]
而且没有发送验证选项，之前的正式版开始有发送验证码选项，后来也是没有了



         原始邮件
         
       
发件人：                  "cx3Y"         ***@***.***&gt;                 
发件时间：         2024年12月15日 10:22 
收件人：                  "cx3Y/sunlogin"         ***@***.***&gt;                 
抄送：                  "99477204"         ***@***.***&gt;         ,                "Author"         ***@***.***&gt;                 
主题：         Re: [cx3Y/sunlogin] P1Pro-V3请求支持 (Issue #5) 




我发布新版本，手动下载release或者在hacs里面点击redownload打开显示beta版本就能更新了

**Comment by 99477204** [comment]
> 我发布新版本，手动下载release或者在hacs里面点击redownload打开显示beta版本就能更新了

P1Pro-V3在3.0.3beta依旧不可用，而且没有发送验证选项，之前的正式版开始有发送验证码选项，后来也是没有了
![Uploading 微信图片_20241215125837.png…]()

**Comment by Scry6** [comment]
能贴一下beta的日志吗，beta有更详细的错误日志

**Comment by cx3Y** [comment]
能贴一下日志吗，beta有更详细的日志

**Comment by 99477204** [comment]
> 能贴一下日志吗，beta有更详细的日志

2024-12-15 14:00:12.346 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 14:00:22.347 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task dns_update
2024-12-15 14:00:22.348 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.001 seconds (success: True)
2024-12-15 14:00:22.436 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] DNS update success, slapi.oray.net: 47.98.232.26
2024-12-15 14:00:32.347 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)

2024-12-15 14:00:42.347 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task config_update
2024-12-15 14:00:42.347 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 14:00:52.347 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插线板P1Pro-V3(738583) status_update
2024-12-15 14:00:52.347 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_status): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-15 14:00:52.348 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插线板P1Pro-V3(738583) electric_update
2024-12-15 14:00:52.348 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_electric): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-15 14:00:52.349 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插座C2-BLE (蓝牙版)(583250) status_update
2024-12-15 14:00:52.349 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插座C2-BLE (蓝牙版)(583250) electric_update
2024-12-15 14:00:52.351 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.004 seconds (success: True)
2024-12-15 14:00:52.681 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_electric): null
2024-12-15 14:00:52.681 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_electric): 'NoneType' object has no attribute 'get'
2024-12-15 14:00:52.931 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_status): null
2024-12-15 14:00:52.931 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_status): 'NoneType' object has no attribute 'get'

2024-12-15 14:01:02.347 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)

2024-12-15 14:01:12.346 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 14:01:22.347 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task devices_update
2024-12-15 14:01:22.348 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.001 seconds (success: True)
2024-12-15 14:01:22.693 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] Devices update success
2024-12-15 14:01:32.347 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)

2024-12-15 14:01:42.347 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)

2024-12-15 14:01:52.347 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插线板P1Pro-V3(738583) status_update
2024-12-15 14:01:52.348 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_status): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-15 14:01:52.348 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插线板P1Pro-V3(738583) electric_update
2024-12-15 14:01:52.349 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_electric): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-15 14:01:52.349 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插座C2-BLE (蓝牙版)(583250) status_update
2024-12-15 14:01:52.350 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插座C2-BLE (蓝牙版)(583250) electric_update
2024-12-15 14:01:52.350 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.003 seconds (success: True)
2024-12-15 14:01:52.666 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_electric): null
2024-12-15 14:01:52.667 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_electric): 'NoneType' object has no attribute 'get'
2024-12-15 14:01:53.537 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_status): null
2024-12-15 14:01:53.537 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_status): 'NoneType' object has no attribute 'get'

我C2没有通电，之前版本正常，这个版本没有测试。P1pro-V3问题依旧

**Comment by 99477204** [comment]
> 能贴一下日志吗，beta有更详细的日志

2024-12-16 16:11:11.918 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-16 16:11:21.919 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插线板P1Pro-V3(738583) status_update
2024-12-16 16:11:21.919 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_status): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-16 16:11:21.920 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插线板P1Pro-V3(738583) electric_update
2024-12-16 16:11:21.920 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_electric): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-16 16:11:21.921 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插座C2-BLE (蓝牙版)(583250) status_update
2024-12-16 16:11:21.921 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插座C2-BLE (蓝牙版)(583250) electric_update
2024-12-16 16:11:21.922 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.003 seconds (success: True)
2024-12-16 16:11:22.229 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_electric): null
2024-12-16 16:11:22.230 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_electric): 'NoneType' object has no attribute 'get'
2024-12-16 16:11:22.479 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_status): null
2024-12-16 16:11:22.479 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_status): 'NoneType' object has no attribute 'get'
2024-12-16 16:11:31.918 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-16 16:11:41.918 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-16 16:11:51.918 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-16 16:12:01.918 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-16 16:12:11.918 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-16 16:12:21.918 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-16 16:12:31.918 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task config_update
2024-12-16 16:12:31.919 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插线板P1Pro-V3(738583) status_update
2024-12-16 16:12:31.919 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_status): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-16 16:12:31.920 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插线板P1Pro-V3(738583) electric_update
2024-12-16 16:12:31.920 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_electric): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-16 16:12:31.921 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插座C2-BLE (蓝牙版)(583250) status_update
2024-12-16 16:12:31.921 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task 智能插座C2-BLE (蓝牙版)(583250) electric_update
2024-12-16 16:12:31.922 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.003 seconds (success: True)
2024-12-16 16:12:32.204 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_electric): null
2024-12-16 16:12:32.204 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_electric): 'NoneType' object has no attribute 'get'
2024-12-16 16:12:32.512 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_status): null
2024-12-16 16:12:32.513 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C2-BLE (蓝牙版) (api.async_get_status): 'NoneType' object has no attribute 'get'
2024-12-16 16:12:41.918 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-16 16:12:51.917 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF4A7K67Q2CSA5B35JA7RJ3V) executing task devices_update
2024-12-16 16:12:51.918 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.001 seconds (success: True)
2024-12-16 16:12:52.261 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] Devices update success
2024-12-16 16:13:01.918 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
