### ISSUE TITLE
大佬，麻烦问一下我已经导入到我的hacs里了，但是具体使用上还是显示不可用是啥情况

### ISSUE THREAD

**Issue by SDAU10434** [cx3Y/sunlogin#6]
![SharedScreenshot](https://github.com/user-attachments/assets/e02415a0-8198-4568-a943-823146287b9e)
现在在手机端不是同一个局域网还是能控制的

**Comment by cx3Y** [comment]
v3不能获取状态的bug还在找原因

**Comment by jayhuangz** [comment]
感谢大佬～～
等信～！

**Comment by cx3Y** [comment]
我发布新版本，手动下载release或者在hacs里面点击redownload打开显示beta版本就能更新了

**Comment by SDAU10434** [comment]
> 我发布新版本，手动下载release或者在hacs里面点击redownload打开显示beta版本就能更新了

太感谢了，麻烦您了

**Comment by SDAU10434** [comment]
> 我发布新版本，手动下载release或者在hacs里面点击redownload打开显示beta版本就能更新了

实在不好意思，是我的设置有问题吗，我这边还是显示不行，我已经更新了beta版本。
2024-12-15 20:08:48.715 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 20:08:48.715 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sunlogin which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 20:08:48.726 ERROR (MainThread) [homeassistant.config_entries] Config entry '101427250' from integration sunlogin has an invalid unique_id '101427250', please create a bug report at https://github.com/cx3Y/sunlogin/issues
2024-12-15 20:09:59.844 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF5369Y3PEH6JW9XZCCBZ8TV) executing task devices_update
2024-12-15 20:09:59.844 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 20:10:00.081 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] Devices update success
2024-12-15 20:10:09.843 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 20:10:19.843 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF5369Y3PEH6JW9XZCCBZ8TV) executing task 智能插座C1Pro-BLE-V3(779799) status_update
2024-12-15 20:10:19.843 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C1Pro-BLE-V3 (api.async_get_status): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-15 20:10:19.843 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF5369Y3PEH6JW9XZCCBZ8TV) executing task 智能插线板P1Pro-V3(294651) status_update
2024-12-15 20:10:19.844 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_status): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-15 20:10:19.844 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF5369Y3PEH6JW9XZCCBZ8TV) executing task 智能插线板P1Pro-V3(294651) electric_update
2024-12-15 20:10:19.844 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_electric): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-15 20:10:19.845 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.003 seconds (success: True)
2024-12-15 20:10:29.843 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 20:10:39.843 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 20:10:49.843 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 20:10:59.843 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF5369Y3PEH6JW9XZCCBZ8TV) executing task config_update
2024-12-15 20:10:59.844 DEBUG (MainThread) [custom_components.sunlogin.updater] StoreManager(01JF5369Y3PEH6JW9XZCCBZ8TV) data write to entry
2024-12-15 20:10:59.844 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.001 seconds (success: True)
2024-12-15 20:11:09.844 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 20:11:19.843 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 20:11:29.843 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF5369Y3PEH6JW9XZCCBZ8TV) executing task 智能插座C1Pro-BLE-V3(779799) status_update
2024-12-15 20:11:29.843 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插座C1Pro-BLE-V3 (api.async_get_status): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-15 20:11:29.843 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF5369Y3PEH6JW9XZCCBZ8TV) executing task 智能插线板P1Pro-V3(294651) status_update
2024-12-15 20:11:29.844 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_status): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-15 20:11:29.844 DEBUG (MainThread) [custom_components.sunlogin.updater] UpdateManager(01JF5369Y3PEH6JW9XZCCBZ8TV) executing task 智能插线板P1Pro-V3(294651) electric_update
2024-12-15 20:11:29.844 DEBUG (MainThread) [custom_components.sunlogin.sunlogin] 智能插线板P1Pro-V3 (api.async_get_electric): unsupported operand type(s) for +: 'NoneType' and 'str'
2024-12-15 20:11:29.845 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.002 seconds (success: True)
2024-12-15 20:11:39.843 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 20:11:49.843 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 20:11:59.843 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)
2024-12-15 20:12:09.844 DEBUG (MainThread) [custom_components.sunlogin.updater] Finished fetching SunloginUpdateScheduler data in 0.000 seconds (success: True)

**Comment by dyanday** [comment]
![wechat_2024-12-24_213920_190](https://github.com/user-attachments/assets/7e802d62-eb4b-4244-b0e4-61526eceb7f2)
大佬，P1pro -v3 无法控制

**Comment by cx3Y** [comment]
v3.0.3-beta2 v3的插座可以用吗

**Comment by Drczhong** [comment]
> v3.0.3-beta2 v3的插座可以用吗

大佬，同请教，不知是否我配置有问题，目前我用的C1-pro插座，直接扫码后没有设备，通过IP添加后控制都是不可用，您那边能正常使用吗，是否有遇到这种情况，使用的是3.0.3版本
![image](https://github.com/user-attachments/assets/989bb318-10a0-49ca-b7e6-e7f040265be6)

**Comment by cx3Y** [comment]
我没v3的设备，@hmqgg提的pr说是地址问题导致v3不可用，而且v3设备不支持本地控制
然后在v3.0.3中添加了默认地址

**Comment by cx3Y** [comment]
> > v3.0.3-beta2 v3的插座可以用吗
> 
> 大佬，同请教，不知是否我配置有问题，目前我用的C1-pro插座，直接扫码后没有设备，通过IP添加后控制都是不可用，您那边能正常使用吗，是否有遇到这种情况，使用的是3.0.3版本 ![image](https://private-user-images.githubusercontent.com/65157009/399089548-989bb318-10a0-49ca-b7e6-e7f040265be6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzOTkwMzEsIm5iZiI6MTczNTM5ODczMSwicGF0aCI6Ii82NTE1NzAwOS8zOTkwODk1NDgtOTg5YmIzMTgtMTBhMC00OWNhLWI3ZTYtZTdmMDQwMjY1YmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDE1MTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYjJiNGY0YWM1Njk4NDNmMGM0OTA5ZmUxNWY5ZjA2NmU0NmZkM2UzNDYxMmE2Y2RmNjljNTI5MDIwNGM5MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6joARiNQLUAEcOD5foacs65rj2SHxHgo1vWznlnKcDs)

看之前的日志c1pro也是v3版本，扫码没设备的问题能提供日志吗，不出设备会有报错

**Comment by hmqgg** [comment]
> > v3.0.3-beta2 v3的插座可以用吗
> 
> 大佬，同请教，不知是否我配置有问题，目前我用的C1-pro插座，直接扫码后没有设备，通过IP添加后控制都是不可用，您那边能正常使用吗，是否有遇到这种情况，使用的是3.0.3版本 ![image](https://private-user-images.githubusercontent.com/65157009/399089548-989bb318-10a0-49ca-b7e6-e7f040265be6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzOTk2MjUsIm5iZiI6MTczNTM5OTMyNSwicGF0aCI6Ii82NTE1NzAwOS8zOTkwODk1NDgtOTg5YmIzMTgtMTBhMC00OWNhLWI3ZTYtZTdmMDQwMjY1YmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDE1MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZTJjNWUwMmZmOGQ4MzE0Y2Q4NDA1YTlkOTNjYzA2OTUzZmFmNTU4ODVlZmIzZjk1OGZhYWMyYzI2NDFlOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wdIUKaPvy3NTKZw5NA4qzJf-p4BkGZba_a22GmEVVhA)

HACS 对 Sunlogin 插件点 `Redownload`，从下拉列表里选 [v3.0.3-beta2](https://github.com/cx3Y/sunlogin/releases/tag/v3.0.3-beta2)，然后再试试

**Comment by cx3Y** [comment]
@hmqgg 你的v3设备可以用吗，beta2和正式版就多了个请求头

**Comment by hmqgg** [comment]
> @hmqgg 你的v3设备可以用吗，beta2和正式版就多了个请求头

我目前 HACS 还是 import 我的 [fork](https://github.com/hmqgg/sunlogin) 暂时没改，能用。 
![image](https://github.com/user-attachments/assets/0a73dcc7-ef4e-449f-bb5c-12ef0012214b)

**Comment by cx3Y** [comment]
> > @hmqgg 你的v3设备可以用吗，beta2和正式版就多了个请求头
> 
> 我目前 HACS 还是 import 我的 [fork](https://github.com/hmqgg/sunlogin) 暂时没改，能用。 
那应该是请求头的问题，beta2是合并pr后发布的，没改代码

**Comment by cx3Y** [comment]
> > v3.0.3-beta2 v3的插座可以用吗
> 
> 大佬，同请教，不知是否我配置有问题，目前我用的C1-pro插座，直接扫码后没有设备，通过IP添加后控制都是不可用，您那边能正常使用吗，是否有遇到这种情况，使用的是3.0.3版本

等一下，我好像看错了，你的设备是v3以前的版本吗，就是向日葵app里产品型号显示C1Pro或者C1Pro-BLE
提供一下设备固件版本，还有ha版本，插件日志
如果是第一次添加就出错，没有向日葵集成这个选项，点击配置-系统-日志，里面会有报错信息

**Comment by Drczhong** [comment]
感谢您的回复，最初情况为：向日葵集成添加没有问题，通过扫码后没有设备，IP添加后有设备但不可用。
![image](https://github.com/user-attachments/assets/52fa8019-eb13-4b58-9880-2bd715eb6c47)
设备版本：
![1735440184255_d](https://github.com/user-attachments/assets/173721f8-ec5c-4413-81ba-d6945a5e5032)
ha版本：
![image](https://github.com/user-attachments/assets/d79249ff-484b-47c2-99f3-0a7f3e531efc)

添加设备后相关日志：
2024-12-29 10:30:27.998 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/sunlogin/sunlogin.py", line 1615, in async_refresh_token
    r_json = resp.json()
             ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'json'
2024-12-29 10:33:58.134 WARNING (MainThread) [homeassistant.data_entry_flow] custom_components.sunlogin.config_flow::SunLoginConfigFlow calls async_show_progress without passing a progress task, this is not valid and will break in Home Assistant Core 2024.8. Please report it to the custom integration author
2024-12-29 10:34:20.888 ERROR (MainThread) [custom_components.sunlogin.config_flow] Cloud API get_devices_list failed: Request failed, status ConnectionError
2024-12-29 10:35:11.036 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/sunlogin/sunlogin.py", line 1615, in async_refresh_token
    r_json = resp.json()
             ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'json'
2024-12-29 10:37:24.703 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/sunlogin/sunlogin.py", line 1615, in async_refresh_token
    r_json = resp.json()
             ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'json'

最新情况为：今早打开ha，发现昨晚重新扫码添加的‘42144630’下面出现了设备，并且可以正常控制，以下是当时的实体截图，但当我尝试重新添加后，依旧跟上述最初的情况一样，后续我再等待看能否再出现：
![1735440427382_d](https://github.com/user-attachments/assets/cda57503-85a5-4db1-80c8-0c0dd79cfb66)

**Comment by cx3Y** [comment]
@Drczhong 都是连接失败，可能是网络波动导致的

**Comment by Drczhong** [comment]
> @Drczhong 都是连接失败，可能是网络波动导致的

感谢，我再多做下尝试

**Comment by Drczhong** [comment]
> @Drczhong 都是连接失败，可能是网络波动导致的

最后尝试到用Clash开TUN模式后，插座实体可以正常使用，但关闭后就只有远程控制这一实体可用，除此之外改DNS等方法都不可行，最后用VMware虚拟机重装HA后可以正常连接插座并控制了。

**Comment by cx3Y** [comment]
你的网络环境这么复杂吗，其实插件有代理选项，可以让插件强行走你的设置的代理，点开选项，翻到最下面就有是否启用代理，不过只支持http代理不支持socks5

**Comment by Drczhong** [comment]
> 你的网络环境这么复杂吗，其实插件有代理选项，可以让插件强行走你的设置的代理，点开选项，翻到最下面就有是否启用代理，不过只支持http代理不支持socks5

主要原因应该是一开始virtualbox虚拟机网络连接有问题，目前VMware用冬瓜的haos开桥接，基本都正常了hh，感谢回复，祝25年万事顺遂！
